"""Generate concept quizzes and interview questions with the local model.

roadmap.sh publishes no assessment material, so every concept imported from it
arrives with an empty quiz. ``routers/progress.py`` treats a concept with no
questions as automatically passed, which means the product's central promise —
that every step ends in a check — is currently false for all 2,757 of them.
This script fills that gap.

Two passes, and the second one is the point
-------------------------------------------
A 7B model asked for five multiple-choice questions about a topic will happily
produce five, whether or not the text in front of it supports them. It pads
with things it knows from pre-training, invents specifics the passage never
states, and occasionally writes a "correct" option that is simply wrong. A
question whose answer cannot be found in the material the learner just read is
worse than no question at all: it fails people for not knowing something the
product never taught them.

So generation is followed by a **grounding check**. Each question is sent back
alone, in a fresh context, with the concept body and its own stated answer, and
the model is asked whether that body actually establishes the answer. Anything
that comes back unsupported is discarded rather than repaired — a rewrite would
be the same model marking its own homework twice. The rejection rate is printed
at the end because it is the honest measure of how much of the first pass was
bluff.

The two question types are held to different bars, which matters more than it
sounds. A multiple-choice question is a *gate*: a learner is failed for getting
it wrong, so nothing beyond the material they were given may be required, and
every distractor has to be defensibly wrong. An interview answer is a *worked
example*, and a good one explains somewhat beyond the notes it came from —
holding it to the quiz standard rejects roughly nine answers in ten for being
fuller than their source rather than for being wrong. It is checked instead for
being correct, on-topic, and free of specifics the source cannot back.

Structural rules are enforced *before* the model is consulted (cheap rejections
first): four distinct options, exactly one marked correct, a real explanation,
no "all of the above", and no vocabulary-recall prompts such as "what does REST
stand for" — which a 7B model reaches for constantly and which test nothing.

Output
------
Authored YAML under ``app/seed/quizzes/<track>.yaml``, keyed by concept slug,
loaded by ``app.seed.loader.seed_quizzes``. Deliberately *not* under
``app/seed/tracks/``: that directory is machine-generated by
``scripts/import_roadmapsh.py``, is git-ignored for licence reasons, and is
overwritten wholesale on the next import. These questions are ours and have to
survive that.

Resuming
--------
The YAML *is* the checkpoint. Each concept is appended and the file rewritten
atomically the moment it is done, so an interrupted run loses at most the
concept in flight. Re-running skips every slug already present, which also
makes this safe to run repeatedly as the target list grows. ``--force``
regenerates concepts that are already covered.

Usage::

    python scripts/generate_quizzes.py --limit 250
    python scripts/generate_quizzes.py --only backend-introduction --force
    python scripts/generate_quizzes.py --concepts my-slugs.txt
    python scripts/generate_quizzes.py --dry-run          # show the plan only
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import OrderedDict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import httpx
import yaml

BACKEND = Path(__file__).resolve().parent.parent
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from sqlalchemy import select  # noqa: E402
from sqlalchemy.orm import Session  # noqa: E402

from app.database import SessionLocal  # noqa: E402
from app.models.company import CompanyFocus  # noqa: E402
from app.models.content import Concept, Track, TrackConcept  # noqa: E402
from app.models.project import Project  # noqa: E402

OUT_DIR = BACKEND / "app" / "seed" / "quizzes"

DEFAULT_MODEL = "qwen2.5:7b"
DEFAULT_BASE_URL = "http://127.0.0.1:11434"

# The role roadmaps people actually start, in the order they matter. DSA comes
# first and separately: it is the track with the most traffic and the one where
# a wrong "correct" answer would be most obviously wrong.
DSA_PREFIX = "dsa-"
ROLE_TRACKS = (
    "backend",
    "frontend",
    "devops",
    "full-stack",
    "data-analyst",
    "cyber-security",
    "machine-learning",
    "ai-engineer",
    "computer-science",
    "system-design",
    "api-design",
)

# How much of a concept body to show the model. Long enough for the whole of
# almost every concept, short enough to keep prompt evaluation off the critical
# path.
MAX_BODY_CHARS = 7000
# Below this there is nothing to build a grounded question on, and the model
# would have to invent the material. Skipped and reported rather than faked.
MIN_BODY_CHARS = 400

ASK_QUIZ = 5
ASK_INTERVIEW = 3
KEEP_QUIZ_MAX = 5
KEEP_INTERVIEW_MAX = 3
# A one-question quiz gates completion on a coin flip, so a concept that cannot
# clear these floors is left uncovered instead of half-covered.
MIN_QUIZ = 3
MIN_INTERVIEW = 2

DIFFICULTIES = ("easy", "medium", "hard")

# Prompts the model reaches for when it has run out of real ideas. Every one of
# these tests whether you have memorised a phrase, not whether you understood
# anything.
VOCAB_PATTERNS = (
    re.compile(r"\bwhat does\b.{0,40}\bstand for\b", re.I),
    re.compile(r"\bis an? acronym\b", re.I),
    re.compile(r"\bwhat is the (full form|abbreviation|expansion)\b", re.I),
    # Questions that only make sense with the source open beside them. The
    # learner sees the question alone, so "according to the notes" is unanswerable.
    re.compile(
        r"\b(according to|as (described|mentioned|stated|listed|noted|shown) in"
        r"|based on|per)\b.{0,20}"
        r"\b(passage|text|content|article|document|notes|material|source)\b",
        re.I,
    ),
    re.compile(r"\bin the (passage|text|content|article|notes|material) above\b", re.I),
    re.compile(r"\b(the |these |your )?(study )?notes\b\s*[?.]?\s*$", re.I),
)
LAZY_OPTIONS = re.compile(
    r"^\s*(all|none|both|any) of (the )?(above|these|them|the options)\s*\.?\s*$", re.I
)
# The model sometimes numbers its own options ("A) PostgreSQL"). The UI renders
# the labels itself, so leaving them in double-labels every option — and it only
# does it for some questions, so the bank ends up inconsistent with itself.
OPTION_LABEL = re.compile(r"^\s*[\(\[]?([A-Da-d]|[1-4])[\)\].:]\s+")


# --------------------------------------------------------------------------
# schemas — Ollama constrains generation to these, so parsing cannot fail
# --------------------------------------------------------------------------

GENERATE_SCHEMA = {
    "type": "object",
    "properties": {
        "quiz": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "prompt": {"type": "string"},
                    "options": {
                        "type": "array",
                        "items": {"type": "string"},
                        "minItems": 4,
                        "maxItems": 4,
                    },
                    "correct_index": {"type": "integer"},
                    "explanation": {"type": "string"},
                },
                "required": ["prompt", "options", "correct_index", "explanation"],
            },
        },
        "interview": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "answer_md": {"type": "string"},
                    "difficulty": {"type": "string", "enum": list(DIFFICULTIES)},
                },
                "required": ["question", "answer_md", "difficulty"],
            },
        },
    },
    "required": ["quiz", "interview"],
}

VERDICT_SCHEMA = {
    "type": "object",
    "properties": {
        "supported": {"type": "boolean"},
        "reason": {"type": "string"},
    },
    "required": ["supported", "reason"],
}


# --------------------------------------------------------------------------
# prompts
# --------------------------------------------------------------------------

GENERATE_SYSTEM = """\
You write assessment questions for a technical learning platform.

You are given one concept's study notes. Everything you write must be answerable
from those notes alone. A learner who has just read them, and knows nothing else,
must be able to get every question right.

Hard rules:
- Test understanding, not vocabulary. Never ask what an abbreviation stands for,
  never ask for a definition the notes state verbatim. Ask why something works,
  when to choose it, what breaks without it, what the trade-off is.
- Exactly one option is correct. The other three must be wrong for a specific
  reason a knowledgeable person could articulate - a plausible confusion, a
  neighbouring technology, an inverted trade-off. Never a joke answer.
- Never write "all of the above", "none of the above" or "both A and B".
- Never refer to "the passage", "the text" or "the notes" in a question. The
  learner sees the question on its own.
- The explanation says why the correct option is correct, in one or two
  sentences, and is useful to someone who got it wrong.
- Interview questions are what a real interviewer would ask about this topic.
  The answer is a genuine answer, three to six sentences, not a restatement of
  the question.

Reply with JSON only."""

GENERATE_USER = """\
Concept: {name}

Study notes:
---
{body}
---

Write exactly {n_quiz} multiple-choice questions and {n_interview} interview \
questions about this concept, all answerable from the notes above."""

VERIFY_QUIZ_SYSTEM = """\
You are checking one exam question against the source material it was written
from. You are strict: your job is to catch questions the source cannot actually
answer, not to be agreeable.

Answer "supported": true only if ALL of these hold:
1. The source material establishes that the marked answer is correct.
2. The source material does not contradict it.
3. Each of the other options is wrong for this question.
4. The question is answerable by someone who has read only this source - it does
   not depend on outside facts, specific numbers, versions or tools the source
   never mentions.

If the marked answer is merely plausible, or is true in general but not
established by the source, answer false. If two options could both be defended
as correct, answer false.

Give a one-sentence reason. Reply with JSON only."""

# A different bar, deliberately. A multiple-choice question is a gate: the
# learner is failed for getting it wrong, so nothing outside the material they
# were given may be required. An interview answer is a worked example, and a
# good one explains a little beyond the notes it came from. Holding it to the
# quiz standard rejects roughly nine answers in ten - not because they are
# wrong, but because they are fuller than the source. What matters here is that
# the answer is correct, is about something the concept actually covers, and
# invents no specifics the source cannot back.
VERIFY_INTERVIEW_SYSTEM = """\
You are checking one interview question and its proposed answer against the
source material the question was written from.

Answer "supported": true only if ALL of these hold:
1. The question is about something the source material actually covers.
2. The answer is factually correct.
3. Nothing in the answer contradicts the source material.
4. The answer invents no specifics - no numbers, versions, benchmarks, tool
   names or claims about behaviour that the source does not support.

An answer may add correct explanation that goes somewhat beyond the source; that
is what a good interview answer does, and it is not grounds for rejection.
Reject an answer for being wrong, for being about a topic this source does not
cover, or for asserting particulars the source cannot back.

Give a one-sentence reason. Reply with JSON only."""

VERIFY_QUIZ_USER = """\
Source material for the concept "{name}":
---
{body}
---

Question: {prompt}

Options:
{options}

Marked correct: {answer}

Is this question supported by the source material above?"""

VERIFY_INTERVIEW_USER = """\
Source material for the concept "{name}":
---
{body}
---

Interview question: {question}

Proposed answer:
{answer}

Is this answer accurate and supported by the source material above? Answer false
if the answer states anything the source contradicts, or anything substantive
the source does not establish."""


# --------------------------------------------------------------------------
# Ollama
# --------------------------------------------------------------------------


class ModelError(RuntimeError):
    """The model could not be reached or returned something unusable."""


class Ollama:
    """Blocking chat client. One request at a time on purpose.

    Concurrency buys nothing here — a single 7B request already saturates the
    GPU, so four in flight finish in four times the wall clock with four times
    the chance of an OOM.
    """

    def __init__(self, base_url: str, model: str, timeout: float = 300.0):
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.client = httpx.Client(timeout=timeout)
        self.calls = 0
        self.tokens = 0

    def close(self) -> None:
        self.client.close()

    def check(self) -> None:
        try:
            response = self.client.get(f"{self.base_url}/api/tags", timeout=10.0)
            response.raise_for_status()
        except httpx.HTTPError as exc:
            raise ModelError(
                f"Ollama is not reachable at {self.base_url} ({exc}). "
                f"Start it with `ollama serve`."
            ) from None
        installed = {m.get("name", "") for m in response.json().get("models", [])}
        if self.model not in installed:
            raise ModelError(
                f"Model '{self.model}' is not installed. Have: "
                f"{', '.join(sorted(installed)) or 'nothing'}. "
                f"Pull it with `ollama pull {self.model}`."
            )

    def json_chat(
        self,
        system: str,
        user: str,
        schema: dict[str, Any],
        *,
        temperature: float,
        attempts: int = 3,
    ) -> dict[str, Any]:
        payload = {
            "model": self.model,
            "stream": False,
            # A JSON schema, not just `"json"`: the sampler is constrained to
            # the grammar, so a malformed reply is impossible rather than
            # merely unlikely.
            "format": schema,
            "options": {"temperature": temperature, "num_ctx": 8192},
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        }
        last: Exception | None = None
        for attempt in range(attempts):
            try:
                response = self.client.post(f"{self.base_url}/api/chat", json=payload)
                response.raise_for_status()
                body = response.json()
                if body.get("error"):
                    raise ModelError(str(body["error"]))
                self.calls += 1
                self.tokens += int(body.get("eval_count") or 0)
                return json.loads(body["message"]["content"])
            except (httpx.HTTPError, json.JSONDecodeError, KeyError, ModelError) as exc:
                last = exc
                if attempt + 1 < attempts:
                    time.sleep(2 * (attempt + 1))
        raise ModelError(f"model call failed after {attempts} attempts: {last}")


# --------------------------------------------------------------------------
# target selection
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Target:
    """A concept, flattened out of the ORM.

    The generation loop runs for hours. Holding a SQLAlchemy session open for
    that long keeps a SQLite read transaction alive and blocks the seeder from
    writing, so everything the loop needs is copied out and the session closed
    before the first model call.
    """

    slug: str
    name: str
    body: str
    track: str


def select_targets(db: Session) -> tuple[list[Target], dict[str, Target]]:
    """The priority queue, plus every concept keyed by slug.

    The queue is ordered by how likely a learner is to hit the concept: the DSA
    track, then the role roadmaps in the order they are picked, then anything a
    company's focus areas or a project points at. Covering all 2,757 concepts
    with a local 7B model would take days; covering the ~250 that appear on
    real routes takes hours and closes the gap where it is visible.

    The second return value exists so ``--only`` and ``--concepts`` can name a
    concept outside that priority set — the ordering is a default, not a fence.
    """
    tracks = db.scalars(select(Track).order_by(Track.sort_order)).all()
    by_slug = {t.slug: t for t in tracks}

    members: dict[str, list[Concept]] = {}
    for track in tracks:
        rows = db.scalars(
            select(Concept)
            .join(TrackConcept, TrackConcept.concept_id == Concept.id)
            .where(TrackConcept.track_id == track.id)
            .order_by(TrackConcept.sort_order)
        ).all()
        members[track.slug] = list(rows)

    ordered: list[str] = [s for s in by_slug if s.startswith(DSA_PREFIX)]
    ordered += [s for s in ROLE_TRACKS if s in by_slug and s not in ordered]

    targets: "OrderedDict[str, Target]" = OrderedDict()
    for track_slug in ordered:
        for concept in members.get(track_slug, []):
            targets.setdefault(concept.slug, _target(concept, track_slug))

    # Whatever the company pages and the projects point at, if a role roadmap
    # has not already claimed it. These are few, and they are exactly the
    # concepts a learner lands on from outside a route.
    referenced: list[Concept] = []
    referenced += list(
        db.scalars(
            select(Concept)
            .join(CompanyFocus, CompanyFocus.concept_id == Concept.id)
            .order_by(Concept.slug)
        ).unique()
    )
    referenced += list(
        db.scalars(
            select(Concept)
            .join(Project, Project.concept_id == Concept.id)
            .order_by(Concept.slug)
        ).unique()
    )
    def home_of(concept: Concept) -> str:
        """The file a concept's questions belong in: its highest-priority track."""
        return next(
            (s for s in ordered if concept in members.get(s, [])),
            None,
        ) or next(
            (t.slug for t in tracks if concept in members.get(t.slug, [])),
            concept.domain.slug,
        )

    for concept in referenced:
        if concept.slug in targets:
            continue
        targets[concept.slug] = _target(concept, home_of(concept))

    everything = dict(targets)
    for concept in db.scalars(select(Concept).order_by(Concept.slug)).unique():
        everything.setdefault(concept.slug, _target(concept, home_of(concept)))

    return list(targets.values()), everything


def _target(concept: Concept, track: str) -> Target:
    text = (concept.content_md or "").strip()
    summary = (concept.summary or "").strip()
    if summary and summary not in text:
        text = f"{summary}\n\n{text}"
    return Target(
        slug=concept.slug, name=concept.name, body=text[:MAX_BODY_CHARS], track=track
    )


# --------------------------------------------------------------------------
# YAML store — one file per track, and the resume checkpoint
# --------------------------------------------------------------------------

FILE_HEADER = """\
# Concept quizzes and interview questions - {track}
#
# Generated by scripts/generate_quizzes.py against each concept's own
# content_md, then re-checked question by question against that same body;
# anything the body could not support was discarded. Loaded by
# app.seed.loader.seed_quizzes and keyed by concept slug.
#
# This file is authored content and belongs in git. Do not move it into
# app/seed/tracks/, which the roadmap.sh importer regenerates.
"""


class QuizStore:
    """The `quizzes/*.yaml` set, treated as both output and progress log."""

    def __init__(self, out_dir: Path):
        self.out_dir = out_dir
        self.files: dict[str, dict[str, Any]] = {}
        self.home: dict[str, str] = {}
        if out_dir.exists():
            for path in sorted(out_dir.glob("*.yaml")):
                data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
                concepts = data.get("concepts") or {}
                self.files[path.stem] = concepts
                for slug in concepts:
                    self.home[slug] = path.stem

    def covered(self) -> set[str]:
        return set(self.home)

    def put(self, track: str, slug: str, payload: dict[str, Any]) -> None:
        # A slug may only live in one file, or the loader rejects the set.
        previous = self.home.get(slug)
        if previous is not None and previous != track:
            self.files[previous].pop(slug, None)
            self._write(previous)
        self.files.setdefault(track, {})[slug] = payload
        self.home[slug] = track
        self._write(track)

    def _write(self, track: str) -> None:
        self.out_dir.mkdir(parents=True, exist_ok=True)
        concepts = self.files[track]
        body = yaml.safe_dump(
            {"concepts": {k: concepts[k] for k in sorted(concepts)}},
            sort_keys=False,
            allow_unicode=True,
            width=100,
            default_flow_style=False,
        )
        text = FILE_HEADER.format(track=track) + "\n" + body
        # Write beside the target and replace: an interrupt during the write of
        # a 200 KB file must not leave a truncated one behind, since this file
        # is the only record of several hours of generation.
        tmp = self.out_dir / f".{track}.yaml.tmp"
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(self.out_dir / f"{track}.yaml")


# --------------------------------------------------------------------------
# structural filtering — the cheap rejections, before the model is consulted
# --------------------------------------------------------------------------


def _clean(text: Any) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def _option_text(text: Any) -> str:
    """One option, without the letter the model may have prefixed it with."""
    return OPTION_LABEL.sub("", _clean(text)).strip()


def structural_reject(question: dict[str, Any]) -> str | None:
    """Why this question is unusable, or None if it survives."""
    prompt = _clean(question.get("prompt"))
    options = [_option_text(o) for o in question.get("options") or []]
    index = question.get("correct_index")
    explanation = _clean(question.get("explanation"))

    if len(prompt) < 15:
        return "prompt too short"
    if len(options) < 4:
        return "fewer than four options"
    if any(not o for o in options):
        return "blank option"
    if len({o.casefold() for o in options}) != len(options):
        return "duplicate options"
    if not isinstance(index, int) or not 0 <= index < len(options):
        return "correct_index out of range"
    if len(explanation) < 30:
        return "explanation too thin"
    if any(pattern.search(prompt) for pattern in VOCAB_PATTERNS):
        return "vocabulary recall, not understanding"
    if any(LAZY_OPTIONS.match(o) for o in options):
        return "'all of the above'-style option"
    # An option that is far longer than the rest gives the answer away.
    longest = max(options, key=len)
    if len(longest) > 3 * min(len(o) for o in options) and len(longest) > 60:
        return "correct option is conspicuously longer"
    return None


def structural_reject_interview(question: dict[str, Any]) -> str | None:
    text = _clean(question.get("question"))
    answer = _clean(question.get("answer_md"))
    if len(text) < 15:
        return "question too short"
    if len(answer) < 120:
        return "answer too thin to be useful"
    if answer.casefold().startswith(text.casefold()[:40]):
        return "answer restates the question"
    if any(pattern.search(text) for pattern in VOCAB_PATTERNS):
        return "vocabulary recall, not understanding"
    return None


# --------------------------------------------------------------------------
# generation + verification
# --------------------------------------------------------------------------


class Tally:
    def __init__(self) -> None:
        self.generated_quiz = 0
        self.generated_interview = 0
        self.structural_quiz = 0
        self.structural_interview = 0
        self.unsupported_quiz = 0
        self.unsupported_interview = 0
        self.kept_quiz = 0
        self.kept_interview = 0

    @property
    def generated(self) -> int:
        return self.generated_quiz + self.generated_interview

    @property
    def kept(self) -> int:
        return self.kept_quiz + self.kept_interview

    @property
    def rejected(self) -> int:
        return self.generated - self.kept


def generate(model: Ollama, target: Target, temperature: float) -> dict:
    return model.json_chat(
        GENERATE_SYSTEM,
        GENERATE_USER.format(
            name=target.name,
            body=target.body,
            n_quiz=ASK_QUIZ,
            n_interview=ASK_INTERVIEW,
        ),
        GENERATE_SCHEMA,
        temperature=temperature,
    )


def verify_quiz(model: Ollama, target: Target, q: dict) -> tuple[bool, str]:
    options = [_option_text(o) for o in q["options"]]
    listed = "\n".join(
        f"{chr(65 + i)}. {text}" for i, text in enumerate(options)
    )
    verdict = model.json_chat(
        VERIFY_QUIZ_SYSTEM,
        VERIFY_QUIZ_USER.format(
            name=target.name,
            body=target.body,
            prompt=_clean(q["prompt"]),
            options=listed,
            answer=options[q["correct_index"]],
        ),
        VERDICT_SCHEMA,
        temperature=0.0,
    )
    return bool(verdict.get("supported")), _clean(verdict.get("reason"))


def verify_interview(model: Ollama, target: Target, q: dict) -> tuple[bool, str]:
    verdict = model.json_chat(
        VERIFY_INTERVIEW_SYSTEM,
        VERIFY_INTERVIEW_USER.format(
            name=target.name,
            body=target.body,
            question=_clean(q["question"]),
            answer=str(q["answer_md"]).strip(),
        ),
        VERDICT_SCHEMA,
        temperature=0.0,
    )
    return bool(verdict.get("supported")), _clean(verdict.get("reason"))


def build_for_concept(
    model: Ollama,
    target: Target,
    tally: Tally,
    *,
    attempts: int,
    verbose: bool,
) -> dict[str, Any] | None:
    """Generate, filter, verify. Returns None when too little survived."""
    quiz: list[dict[str, Any]] = []
    interview: list[dict[str, Any]] = []
    seen_prompts: set[str] = set()
    seen_questions: set[str] = set()

    for attempt in range(attempts):
        if len(quiz) >= MIN_QUIZ and len(interview) >= MIN_INTERVIEW:
            break
        # Nudge the temperature up on a retry: repeating the first pass at the
        # same setting mostly reproduces the questions that were just rejected.
        raw = generate(model, target, temperature=0.3 + 0.2 * attempt)

        for q in raw.get("quiz") or []:
            if len(quiz) >= KEEP_QUIZ_MAX:
                break
            tally.generated_quiz += 1
            key = _clean(q.get("prompt")).casefold()
            if key in seen_prompts:
                tally.structural_quiz += 1
                continue
            seen_prompts.add(key)
            why = structural_reject(q)
            if why:
                tally.structural_quiz += 1
                if verbose:
                    print(f"      drop mcq  [{why}] {_clean(q.get('prompt'))[:70]}")
                continue
            supported, reason = verify_quiz(model, target, q)
            if not supported:
                tally.unsupported_quiz += 1
                if verbose:
                    print(f"      drop mcq  [unsupported] {reason[:90]}")
                continue
            options = [_option_text(o) for o in q["options"]]
            quiz.append(
                {
                    "prompt": _clean(q["prompt"]),
                    "explanation": _clean(q["explanation"]),
                    "options": [
                        {"text": text, "correct": True}
                        if i == q["correct_index"]
                        else {"text": text}
                        for i, text in enumerate(options)
                    ],
                }
            )
            tally.kept_quiz += 1

        for q in raw.get("interview") or []:
            if len(interview) >= KEEP_INTERVIEW_MAX:
                break
            tally.generated_interview += 1
            key = _clean(q.get("question")).casefold()
            if key in seen_questions:
                tally.structural_interview += 1
                continue
            seen_questions.add(key)
            why = structural_reject_interview(q)
            if why:
                tally.structural_interview += 1
                if verbose:
                    print(f"      drop iq   [{why}] {_clean(q.get('question'))[:70]}")
                continue
            supported, reason = verify_interview(model, target, q)
            if not supported:
                tally.unsupported_interview += 1
                if verbose:
                    print(f"      drop iq   [unsupported] {reason[:90]}")
                continue
            difficulty = str(q.get("difficulty") or "medium").lower()
            interview.append(
                {
                    "question": _clean(q["question"]),
                    "answer_md": str(q["answer_md"]).strip(),
                    "difficulty": difficulty
                    if difficulty in DIFFICULTIES
                    else "medium",
                }
            )
            tally.kept_interview += 1

    if len(quiz) < MIN_QUIZ or len(interview) < MIN_INTERVIEW:
        # Roll back what did survive: a two-question quiz that a learner can
        # pass by guessing is a worse gate than the honest no-gate fallback.
        tally.kept_quiz -= len(quiz)
        tally.kept_interview -= len(interview)
        return None

    return {
        "generated_by": model.model,
        "verified_at": datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "quiz": quiz,
        "interview": interview,
    }


# --------------------------------------------------------------------------
# entrypoint
# --------------------------------------------------------------------------


def _read_slug_file(path: Path) -> list[str]:
    slugs = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            slugs.append(line)
    return slugs


def _filter(
    targets: list[Target],
    everything: dict[str, Target],
    *,
    only: list[str],
    from_file: Path | None,
) -> list[Target]:
    """Narrow the priority queue to an explicitly named set, if one was given.

    Named slugs are resolved against every concept, not just the priority set,
    so a run can cover something the ordering has not reached yet. An unknown
    slug is fatal rather than skipped: silently generating for four of the five
    concepts you asked for is the kind of thing you only notice much later.
    """
    wanted: list[str] = list(only)
    if from_file is not None:
        wanted += _read_slug_file(from_file)
    if not wanted:
        return targets

    picked: list[Target] = []
    missing: list[str] = []
    for slug in dict.fromkeys(wanted):
        if slug in everything:
            picked.append(everything[slug])
        else:
            missing.append(slug)
    if missing:
        raise SystemExit("No such concept: " + ", ".join(missing))
    return picked


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate and verify concept quizzes with a local Ollama model."
    )
    parser.add_argument("--limit", type=int, default=250,
                        help="stop after this many concepts (default: 250)")
    parser.add_argument("--only", action="append", default=[], metavar="SLUG",
                        help="generate for this concept only; repeatable")
    parser.add_argument("--concepts", type=Path, metavar="FILE",
                        help="file of concept slugs, one per line (# comments ok)")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--attempts", type=int, default=2,
                        help="generation passes per concept before giving up")
    parser.add_argument("--force", action="store_true",
                        help="regenerate concepts that already have questions")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the plan and exit without calling the model")
    parser.add_argument("--quiet", action="store_true",
                        help="do not print each rejected question")
    args = parser.parse_args(list(argv) if argv is not None else None)

    # Read the plan, then let go of the database. The loop below runs for hours
    # and would otherwise hold a SQLite read transaction open the whole time,
    # blocking `python -m app.seed.loader` from ever committing.
    db = SessionLocal()
    try:
        priority, everything = select_targets(db)
        targets = _filter(
            priority, everything, only=args.only, from_file=args.concepts
        )
    finally:
        db.close()

    store = QuizStore(OUT_DIR)
    covered = store.covered()

    queue: list[Target] = []
    skipped_short: list[str] = []
    for target in targets:
        if target.slug in covered and not args.force:
            continue
        if len(target.body) < MIN_BODY_CHARS:
            skipped_short.append(target.slug)
            continue
        queue.append(target)
        if len(queue) >= args.limit:
            break

    print(f"{len(targets)} concepts in the target set, "
          f"{len(covered)} already covered, "
          f"{len(skipped_short)} skipped as too short to ground a question.")
    print(f"Queue: {len(queue)} concepts.")
    if args.dry_run:
        for target in queue:
            print(f"  {target.track:20} {target.slug}")
        return 0
    if not queue:
        return 0

    model = Ollama(args.base_url, args.model)
    model.check()

    tally = Tally()
    done = thin = 0
    started = time.time()
    try:
        for position, target in enumerate(queue, start=1):
            elapsed = time.time() - started
            rate = elapsed / max(position - 1, 1)
            eta = rate * (len(queue) - position + 1) / 60
            print(f"[{position}/{len(queue)}] {target.slug} "
                  f"({target.track}, ~{eta:.0f} min left)", flush=True)
            try:
                payload = build_for_concept(
                    model, target, tally,
                    attempts=args.attempts, verbose=not args.quiet,
                )
            except ModelError as exc:
                print(f"      SKIPPED: {exc}", flush=True)
                continue
            if payload is None:
                thin += 1
                print("      SKIPPED: too little survived verification", flush=True)
                continue
            store.put(target.track, target.slug, payload)
            done += 1
            print(f"      kept {len(payload['quiz'])} mcq + "
                  f"{len(payload['interview'])} interview", flush=True)
    except KeyboardInterrupt:
        print("\nInterrupted. Everything finished so far is already on disk; "
              "re-run to continue.")

    minutes = (time.time() - started) / 60
    rate = 100 * tally.rejected / tally.generated if tally.generated else 0.0
    unsupported = tally.unsupported_quiz + tally.unsupported_interview
    print(
        f"\n{done} concepts written, {thin} left uncovered "
        f"(too little survived), in {minutes:.0f} min.\n"
        f"Questions generated:   {tally.generated} "
        f"({tally.generated_quiz} mcq, {tally.generated_interview} interview)\n"
        f"Kept:                  {tally.kept} "
        f"({tally.kept_quiz} mcq, {tally.kept_interview} interview)\n"
        f"Rejected structurally: "
        f"{tally.structural_quiz + tally.structural_interview}\n"
        f"Rejected as unsupported by their own source: {unsupported}\n"
        f"Overall rejection rate: {rate:.1f}%\n"
        f"Model calls: {model.calls}, {model.tokens} tokens generated."
    )
    model.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
