"""Projects, companies, points ledger; drop assessment

Revision ID: 3a725c2a4a4e
Revises: e8eb853fc117
Create Date: 2026-07-31 23:26:55.704789
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a725c2a4a4e'
down_revision: Union[str, None] = 'e8eb853fc117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('hq', sa.String(length=160), nullable=True),
    sa.Column('website', sa.String(length=400), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hiring_process_md', sa.Text(), nullable=True),
    sa.Column('fetched_on', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    op.create_table('company_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_resources_company_id'), ['company_id'], unique=False)

    op.create_table('company_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('focus_md', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'slug', name='uq_company_role_slug')
    )
    with op.batch_alter_table('company_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_roles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_roles_slug'), ['slug'], unique=False)

    op.create_table('points_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_slug', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_events_user_id'), ['user_id'], unique=False)

    op.create_table('company_focus_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_role_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_role_id'], ['company_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_focus_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_focus_areas_company_role_id'), ['company_role_id'], unique=False)

    op.create_table('company_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_role_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('round', sa.String(length=24), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_role_id'], ['company_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_questions_company_role_id'), ['company_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_questions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_questions_round'), ['round'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=False),
    sa.Column('brief_md', sa.Text(), nullable=False),
    sa.Column('runtime', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('solution_md', sa.Text(), nullable=True),
    sa.Column('must_contain', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_runtime'), ['runtime'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_entry', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path', name='uq_project_file_path')
    )
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_files_project_id'), ['project_id'], unique=False)

    op.create_table('project_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('files_json', sa.Text(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_submissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_submissions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('project_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tests_project_id'), ['project_id'], unique=False)

    op.drop_table('assessment_questions')
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_results_user_id')

    op.drop_table('assessment_results')
    with op.batch_alter_table('assessment_options', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_options_category')
        batch_op.drop_index('ix_assessment_options_question_id')

    op.drop_table('assessment_options')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        # server_default backfills existing profiles; the column is NOT NULL,
        # and every one of them was already on the 2h/day default.
        batch_op.add_column(
            sa.Column(
                'pace',
                sa.String(length=20),
                nullable=False,
                server_default='steady',
            )
        )
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('target_date')
        batch_op.drop_column('pace')

    op.create_table('assessment_options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=60), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_options', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_options_question_id', ['question_id'], unique=False)
        batch_op.create_index('ix_assessment_options_category', ['category'], unique=False)

    op.create_table('assessment_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('scores_json', sa.TEXT(), nullable=False),
    sa.Column('top_category', sa.VARCHAR(length=60), nullable=False),
    sa.Column('recommended_track_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_results_user_id', ['user_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tests_project_id'))

    op.drop_table('project_tests')
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_submissions_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_project_submissions_created_at'))

    op.drop_table('project_submissions')
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_files_project_id'))

    op.drop_table('project_files')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_runtime'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_concept_id'))

    op.drop_table('projects')
    with op.batch_alter_table('company_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_questions_round'))
        batch_op.drop_index(batch_op.f('ix_company_questions_kind'))
        batch_op.drop_index(batch_op.f('ix_company_questions_id'))
        batch_op.drop_index(batch_op.f('ix_company_questions_company_role_id'))

    op.drop_table('company_questions')
    with op.batch_alter_table('company_focus_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_focus_areas_company_role_id'))

    op.drop_table('company_focus_areas')
    with op.batch_alter_table('points_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_events_kind'))
        batch_op.drop_index(batch_op.f('ix_points_events_id'))
        batch_op.drop_index(batch_op.f('ix_points_events_created_at'))

    op.drop_table('points_events')
    with op.batch_alter_table('company_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_roles_slug'))
        batch_op.drop_index(batch_op.f('ix_company_roles_id'))
        batch_op.drop_index(batch_op.f('ix_company_roles_company_id'))

    op.drop_table('company_roles')
    with op.batch_alter_table('company_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_resources_company_id'))

    op.drop_table('company_resources')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_industry'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    # ### end Alembic commands ###
