"""resume profile, uploads and analyses

Adds the three tables behind Phase 2a.

``resume_profiles`` is the contact block — the only self-reported part of a
generated résumé. Nothing else about a generated résumé is stored: the skills,
projects and readiness on it are read live from ``user_progress``,
``project_submissions`` and ``role_skills`` at render time, so a résumé cannot
drift out of step with the evidence behind it.

``resume_uploads`` holds a file someone uploaded, bytes and all. The bytes live
in the database rather than on disk deliberately: an upload directory inside
the repo would be walked by the seeder and by git, and one outside it would
outlive the row describing it. Every row is scoped to a user and cascades with
the account.

``resume_analyses`` caches the report for one upload. It carries ``degraded``
and ``generated_by`` for the same reason ``quiz_questions`` does — the UI has to
be able to say whether a reader is looking at model output or at arithmetic.

Autogenerated against a working tree where other Phase 2 features were landing
in parallel; their tables were removed from this revision so each migration
owns only its own feature.

Revision ID: e816317eb75b
Revises: a1c7d4e9b208
Create Date: 2026-08-21 18:24:46.921402
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e816317eb75b"
down_revision: Union[str, None] = "a1c7d4e9b208"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "resume_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=True),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=60), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("links", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_profiles_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_profiles_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "resume_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("extraction_ok", sa.Boolean(), nullable=False),
        sa.Column("extraction_note", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_uploads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_uploads_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_resume_uploads_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_resume_uploads_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_uploads_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "resume_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_role_slug", sa.String(length=80), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("generated_by", sa.String(length=80), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["resume_uploads.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resume_analyses_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_resume_analyses_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_resume_analyses_upload_id"), ["upload_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resume_analyses_user_id"), ["user_id"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("resume_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_analyses_user_id"))
        batch_op.drop_index(batch_op.f("ix_resume_analyses_upload_id"))
        batch_op.drop_index(batch_op.f("ix_resume_analyses_id"))
        batch_op.drop_index(batch_op.f("ix_resume_analyses_created_at"))
    op.drop_table("resume_analyses")

    with op.batch_alter_table("resume_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_uploads_user_id"))
        batch_op.drop_index(batch_op.f("ix_resume_uploads_kind"))
        batch_op.drop_index(batch_op.f("ix_resume_uploads_id"))
        batch_op.drop_index(batch_op.f("ix_resume_uploads_created_at"))
    op.drop_table("resume_uploads")

    with op.batch_alter_table("resume_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_resume_profiles_id"))
    op.drop_table("resume_profiles")
