"""initial schema

Revision ID: e8eb853fc117
Revises: 
Create Date: 2026-07-31 21:27:25.379714
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8eb853fc117'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_content', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('assessment_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_options_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_options_question_id'), ['question_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('est_hours', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_slug'), ['slug'], unique=True)

    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('concepts_completed', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_user_day')
    )
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activity_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_user_id'), ['user_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_slug'), ['slug'], unique=True)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_slug', sa.String(length=80), nullable=False),
    sa.Column('badge_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_slug', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_slug'), ['badge_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('top_category', sa.String(length=60), nullable=False),
    sa.Column('recommended_track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_results_user_id'), ['user_id'], unique=False)

    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_user_id'), ['user_id'], unique=False)

    op.create_table('concept_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_embeddings_concept_id'), ['concept_id'], unique=False)

    op.create_table('concept_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'prerequisite_id', name='uq_concept_prereq')
    )
    with op.batch_alter_table('concept_prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_prerequisites_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_prerequisites_prerequisite_id'), ['prerequisite_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_concept_id'), ['concept_id'], unique=False)

    op.create_table('post_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_vote')
    )
    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_votes_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_concept_id'), ['concept_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_kind'), ['kind'], unique=False)

    op.create_table('role_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'concept_id', name='uq_role_skill')
    )
    with op.batch_alter_table('role_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_skills_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_skills_role_id'), ['role_id'], unique=False)

    op.create_table('track_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'concept_id', name='uq_track_concept')
    )
    with op.batch_alter_table('track_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_concepts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_concepts_track_id'), ['track_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_goal', sa.String(length=255), nullable=True),
    sa.Column('current_track_id', sa.Integer(), nullable=True),
    sa.Column('daily_hours', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['current_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_user_concept_progress')
    )
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('daily_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roadmaps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roadmaps_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_options_question_id'), ['question_id'], unique=False)

    op.create_table('user_roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['user_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'concept_id', name='uq_roadmap_concept')
    )
    with op.batch_alter_table('user_roadmap_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roadmap_items_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roadmap_items_roadmap_id'), ['roadmap_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roadmap_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roadmap_items_roadmap_id'))
        batch_op.drop_index(batch_op.f('ix_user_roadmap_items_concept_id'))

    op.drop_table('user_roadmap_items')
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_options_question_id'))

    op.drop_table('quiz_options')
    with op.batch_alter_table('user_roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roadmaps_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roadmaps_id'))

    op.drop_table('user_roadmaps')
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_concept_id'))

    op.drop_table('user_progress')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('track_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_concepts_track_id'))
        batch_op.drop_index(batch_op.f('ix_track_concepts_concept_id'))

    op.drop_table('track_concepts')
    with op.batch_alter_table('role_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_skills_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_skills_concept_id'))

    op.drop_table('role_skills')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_kind'))
        batch_op.drop_index(batch_op.f('ix_resources_concept_id'))

    op.drop_table('resources')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_concept_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_votes_post_id'))

    op.drop_table('post_votes')
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_concept_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('concept_prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_prerequisites_prerequisite_id'))
        batch_op.drop_index(batch_op.f('ix_concept_prerequisites_concept_id'))

    op.drop_table('concept_prerequisites')
    with op.batch_alter_table('concept_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_embeddings_concept_id'))

    op.drop_table('concept_embeddings')
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_post_id'))

    op.drop_table('community_comments')
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_results_user_id'))

    op.drop_table('assessment_results')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_slug'))

    op.drop_table('user_badges')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_slug'))
        batch_op.drop_index(batch_op.f('ix_tracks_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_day'))

    op.drop_table('daily_activity')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_slug'))
        batch_op.drop_index(batch_op.f('ix_concepts_id'))

    op.drop_table('concepts')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_domain_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))

    op.drop_table('community_posts')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('assessment_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_options_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_options_category'))

    op.drop_table('assessment_options')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_slug'))

    op.drop_table('roles')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_slug'))
        batch_op.drop_index(batch_op.f('ix_domains_id'))
        batch_op.drop_index(batch_op.f('ix_domains_category'))

    op.drop_table('domains')
    op.drop_table('assessment_questions')
    # ### end Alembic commands ###
